#Доступные фигуры: SPHERE, CUBE, RECTANGLE
#При запуске плагина, в инициализации анимаций параметр particle-count будет подстраиваться под размер фигур,
#чтобы не было багов с отображением. Проверка может быть бесконечной если в конфиге ввести число партиклов,
#которое будет слишком большим для фигуры данных размеров

animations:
  animation_1:
    duration: 100
    particle-type: REDSTONE
    particle-count: 100
    size: 2
    speed: 1
    shape:
      - CUBE
    cords:
      - 1 0 1